### ISSUE TITLE
Nothing sent out from defmt on STM32WLxx

### ISSUE THREAD

**Issue by huming2207** [gauteh/defmt-serial#1]
Hi @gauteh 

Firstly, thanks for your great work! 

I've had a try with it on one of my STM32WLxx PoC projects. However, it seems like nothing has been committed to UART.  Here are my attempts:

- I've tried doing something like `embedded_hal_serial_Write::write(&mut uart, 0x55)` and I can see the 0x55 printed as ASCII character `U` in the serial monitor. Therefore I guess the peripheral setup and hardware wiring should be correct. 
- I've also tried `defmt-rtt` before and it works fine as well. 
- I've also tried using `cortex-m-rt` only instead of using RTIC. But that didn't work as well. 

Here's my repo: https://github.com/huming2207/lowu/tree/25c9075b1393456c0785ac18f295e49cd54ab79a

Maybe I forgot to add in some initialization stuff?

Regards,
Jackson

**Comment by gauteh** [comment]
Hi Jackson,

Thanks for trying this out. I had a quick look and I don't see anything immediately off in your code. Just to make sure, you have DEFMT_LOG set to something verbose?

Also, do the example-std example work for you?

You could also try an earlier version that relies on a macro and see if I messed something up recently.

I have an stm32 board, but won't have access to test before in a couple of weeks.

Regards, Gaute

**Comment by gauteh** [comment]
If the serial port is dropped for some reason after initialization it usually won't work, I'm trying to prevent that, but its possible there's a bug there.

**Comment by huming2207** [comment]
Hi @gauteh 

> you have DEFMT_LOG set to something verbose?

Yes. I did something like `export DEFMT_LOG=debug` and log with `defmt::info` etc. I've also tried using [tio](https://github.com/tio/tio) to log the raw bytes output. But nothing split out as well. 

> If the serial port is dropped for some reason after initialization it usually won't work, I'm trying to prevent that, but it's possible there's a bug there.

I will have a try tonight and see what will happen if I put the UART object into the shared context.

> You could also try an earlier version that relies on a macro and see if I messed something up recently.

Yep, I also tried v0.3.0, didn't work for me.

> do the example-std example work for you? 

I will try this again as well.

Regards,
Jackson

**Comment by huming2207** [comment]
Hi @gauteh 

I've also tried putting the UART object to the RTIC local context and then use v0.3.0, but still no luck. Here's the code: https://github.com/huming2207/lowu-rs/tree/9b55bc4863d919b0c6b70e62fd8ad7261ab27bb6

Regards,
Jackson

**Comment by gauteh** [comment]
I think the defmt::warn will be called before the serial is assigned, could cause issues. Do you see if the code is working? I.e. the idle loop is running and not optimized away (not sure if asm::nop is still needed), does the continue stop the loop? Maybe toggling a led there and some defmt output with delay, if possible could help debug the issue.

Otherwise, I think I made the major changes from v 0.2.0 to 0.3.0, so if you have the chance could you please try that version?

**Comment by gauteh** [comment]
I found an issue in 0.4.0, but it worked in previous versions, and I think it should be fixed again now in 0.5.0.

**Comment by huming2207** [comment]
Hi @gauteh 

Sorry, I forgot to reply to you earlier. I've tried upgrading 0.5.0 and it still has no output. I've also tried removing the "defmt" feature in the `stm32wlxx-hal` crate in case there's a conflict, but it still doesn't work.

Regards,
Jackson

**Comment by jorgeig-space** [comment]
Hi @huming2207, I found this via the stm32-rs/stm32wlxx-hal#339 issue. I can't try it now, but I believe there are a couple of changes needed for it to work:
* You can't log with defmt before configuring the logger, as @gauteh mentioned. You are calling defmt [here](https://github.com/huming2207/lowu-rs/blob/9b55bc4863d919b0c6b70e62fd8ad7261ab27bb6/src/bin/lowu_main.rs#L54) and the re-assigning the defmt logger [here](https://github.com/huming2207/lowu-rs/blob/9b55bc4863d919b0c6b70e62fd8ad7261ab27bb6/src/bin/lowu_main.rs#L76).
* `defmt_serial::defmt_serial` call should happen at init, not at the loop: it's a consequence of the point above - you can only assign and configure the logger *before* logging anything.
* If you're only using the UART for defmt logging, you don't need to keep the reference in the RTIC context; just use it at init.

Hope this helps!

**Comment by huming2207** [comment]
Hi @jorgeig-space 

Thanks for your info. I forgot to push the latest changes and now here's what I've done earlier: https://github.com/huming2207/lowu-rs/blob/48a29e3276c173b8f61b1bb2d7d15089d239a7c6/src/bin/lowu_main.rs

I've tried putting the `defmt_serial::defmt_serial` at init but it still doesn't work somehow.

Regards,
Jackson

**Comment by gauteh** [comment]
I think the defmt::warn will be called before the serial is assigned, could
cause issues. Do you see if the code is working? I.e. the idle loop is
running and not optimized away (not sure if asm::nop is still needed), does
the continue stop the loop? Maybe toggling a led there and some defmt
output with delay, if possible could help debug the issue.

Otherwise, I think I made the major changes from v 0.2.0 to 0.3.0, so if
you have the chance could you please try that version?

man. 25. jul. 2022, 14:25 skrev Jackson Ming Hu ***@***.***>:

**Comment by gauteh** [comment]
Are you on Mac Os by any chance?

**Comment by huming2207** [comment]
> Are you on Mac Os by any chance?

No, I was using Ubuntu 22.04, and I remember I've tried a few different dongles including CH340, CP2102 and a DAPLink's UART.

**Comment by gauteh** [comment]
Ok, thanks. Then it must be something else.

**Comment by gauteh** [comment]
Maybe related to #9

**Comment by gauteh** [comment]
Closing, hopefully fixed by #9. Reopen if still an issue.
